In [2]:
import os
import sys
import re
import pdb

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
print(os.path.join('hello', 'there'))

hello/there


In [4]:
datasets = ['boston', 'concrete', 'energy', 'kin8nm', 'naval', 'power', 'protein', 'wine_red']
results_dir = '../results'

layers = ['2', '3', '4', '5']

In [5]:
layers = ['2', '3', '4', '5']
mean_nlls = np.ndarray(shape=(len(datasets), len(layers)))
std_nlls = np.ndarray(shape=(len(datasets), len(layers)))
for layer in layers:
    for dataset in datasets:
        filename = dataset + '_' + layer + '_' + '100'
        path = os.path.join(results_dir, filename)
        nll_path = path + '.nll'
        rmse_path = path + '.rsme'
        time_path = path + '.time'
        
        if os.path.isfile(nll_path):
            with open(nll_path, 'r') as f:
                s = f.read()
                results = re.findall('Split\s[0-9]*:\s(.*)\n', s, re.MULTILINE)
            results = [float(result) for result in results if result != 'nan']
            mean_nlls[datasets.index(dataset), layers.index(layer)] = np.mean(results)
            std_nlls[datasets.index(dataset), layers.index(layer)] = np.std(results)

In [6]:
print(mean_nlls)
print(std_nlls)

[[-2.50172919 -2.49960135 -2.49843954 -2.50177852]
 [-3.17555032 -3.14674014 -3.13417215 -3.13581276]
 [-0.68167035 -0.76355    -0.72641257 -0.71844969]
 [ 1.34235157  1.36774536  1.34590753  1.34655501]
 [ 6.68811112  6.80966218  6.60651407  6.74691987]
 [-2.75085287 -2.72335247 -2.72247682 -2.72304534]
 [-2.78823197 -2.71633324 -2.69396011 -2.69354177]
 [-0.94971816 -0.95025551 -0.95017829 -0.95122159]]
[[0.19906187 0.18974061 0.18817958 0.1845805 ]
 [0.06949214 0.07741877 0.07144115 0.07504127]
 [0.10987676 0.09832481 0.09595388 0.09522263]
 [0.02089764 0.0232969  0.01723028 0.02392997]
 [0.41539541 0.28031112 0.97416569 0.24255909]
 [0.03919197 0.04355459 0.03995322 0.03718159]
 [0.01044007 0.01191885 0.01208744 0.01197033]
 [0.05750476 0.0572139  0.05687146 0.05693198]]


In [20]:
datasets = ['boston', 'concrete', 'energy', 'kin8nm', 'naval', 'power', 'protein', 'wine_red']
results_dir = '../aep_results/'

layers = ['2']

aep_mean_nlls = np.ndarray(shape=(len(datasets), len(layers)))
aep_std_nlls = np.ndarray(shape=(len(datasets), len(layers)))
for layer in layers:
    for dataset in datasets:
        filename = 'aep_' + dataset + '_' + layer + '_' + '100'
        path = os.path.join(results_dir, filename)
        nll_path = path + '.nll'
        rmse_path = path + '.rsme'
        time_path = path + '.time'
                
        if os.path.isfile(nll_path):
            with open(nll_path, 'r') as f:
                s = f.read()
                results = re.findall('Split\s[0-9]*:\s(.*)\n', s, re.MULTILINE)
            results = [float(result) for result in results if result != 'nan']
            aep_mean_nlls[datasets.index(dataset), layers.index(layer)] = np.mean(results)
            aep_std_nlls[datasets.index(dataset), layers.index(layer)] = np.std(results)

In [21]:
print(aep_mean_nlls)
print(aep_std_nlls)

[[-2.36195149]
 [-3.16992435]
 [-1.40926433]
 [ 0.96440807]
 [ 0.72751434]
 [-2.85642549]
 [-2.96869672]
 [-0.94461939]]
[[0.12254153]
 [0.06284828]
 [0.05975631]
 [0.03116211]
 [0.00129857]
 [0.01361348]
 [0.01093279]
 [0.06939394]]
